# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "aac2f7f86c7abedbf4aab51ed13021f93a1ab515"

[[deps.DomcsisEpicTinkerBox]]
path = "."
uuid = "e045975a-8055-4875-baa9-f499549805c3"
version = "0.1.0"
