name = "DomcsisEpicTinkerBox"
uuid = "e045975a-8055-4875-baa9-f499549805c3"
authors = ["Dominik Szombathy"]
version = "0.1.0"

[deps]

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]